# Generated by Django 5.2.10 on 2026-01-16 11:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(verbose_name='ID предмета')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('durability', models.PositiveIntegerField(default=100, verbose_name='Прочность (%)')),
                ('acquired_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата получения')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Тип предмета')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to=settings.AUTH_USER_MODEL, verbose_name='Игрок')),
            ],
            options={
                'verbose_name': 'Предмет инвентаря',
                'verbose_name_plural': 'Предметы инвентаря',
                'unique_together': {('player', 'content_type', 'object_id')},
            },
        ),
        migrations.CreateModel(
            name='PlayerEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bait', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipped_as_bait', to='inventory.inventoryitem', verbose_name='Наживка')),
                ('line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipped_as_line', to='inventory.inventoryitem', verbose_name='Леска')),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to=settings.AUTH_USER_MODEL, verbose_name='Игрок')),
                ('reel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipped_as_reel', to='inventory.inventoryitem', verbose_name='Катушка')),
                ('rod', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipped_as_rod', to='inventory.inventoryitem', verbose_name='Удочка')),
            ],
            options={
                'verbose_name': 'Экипировка игрока',
                'verbose_name_plural': 'Экипировки игроков',
            },
        ),
    ]
