# Generated by Django 5.2.10 on 2026-01-16 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='equipment/baits/', verbose_name='Изображение')),
                ('bait_type', models.CharField(choices=[('live', 'Живая наживка'), ('artificial', 'Искусственная'), ('dough', 'Тесто/Паста'), ('natural', 'Натуральная')], default='natural', max_length=20, verbose_name='Тип')),
                ('uses', models.PositiveIntegerField(help_text='На сколько забросов хватает', verbose_name='Количество использований')),
                ('attraction_bonus', models.PositiveIntegerField(default=0, verbose_name='Бонус привлекательности (%)')),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
                ('required_level', models.PositiveIntegerField(default=1, verbose_name='Требуемый уровень')),
                ('is_consumable', models.BooleanField(default=True, verbose_name='Расходуемая')),
            ],
            options={
                'verbose_name': 'Наживка',
                'verbose_name_plural': 'Наживки',
                'ordering': ['bait_type', 'price'],
            },
        ),
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='equipment/lines/', verbose_name='Изображение')),
                ('tier', models.CharField(choices=[('basic', 'Базовое'), ('amateur', 'Любительское'), ('professional', 'Профессиональное'), ('expert', 'Экспертное'), ('master', 'Мастерское')], default='basic', max_length=20, verbose_name='Уровень')),
                ('breaking_strength', models.FloatField(verbose_name='Разрывная нагрузка (кг)')),
                ('visibility', models.PositiveIntegerField(help_text='Чем ниже, тем лучше клёв', verbose_name='Заметность (1-100)')),
                ('stretch', models.PositiveIntegerField(help_text='Высокая = больше прощает ошибки', verbose_name='Растяжимость (1-100)')),
                ('length', models.PositiveIntegerField(verbose_name='Длина (м)')),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
                ('required_level', models.PositiveIntegerField(default=1, verbose_name='Требуемый уровень')),
            ],
            options={
                'verbose_name': 'Леска',
                'verbose_name_plural': 'Лески',
                'ordering': ['required_level', 'price'],
            },
        ),
        migrations.CreateModel(
            name='Reel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='equipment/reels/', verbose_name='Изображение')),
                ('tier', models.CharField(choices=[('basic', 'Базовое'), ('amateur', 'Любительское'), ('professional', 'Профессиональное'), ('expert', 'Экспертное'), ('master', 'Мастерское')], default='basic', max_length=20, verbose_name='Уровень')),
                ('gear_ratio', models.FloatField(help_text='Скорость подмотки (например 5.2:1)', verbose_name='Передаточное число')),
                ('drag_power', models.FloatField(help_text='Максимальное сопротивление', verbose_name='Сила фрикциона (кг)')),
                ('line_capacity', models.PositiveIntegerField(verbose_name='Вместимость лески (м)')),
                ('retrieve_speed', models.PositiveIntegerField(verbose_name='Скорость подмотки (1-100)')),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
                ('required_level', models.PositiveIntegerField(default=1, verbose_name='Требуемый уровень')),
                ('durability', models.PositiveIntegerField(default=100, verbose_name='Прочность')),
            ],
            options={
                'verbose_name': 'Катушка',
                'verbose_name_plural': 'Катушки',
                'ordering': ['required_level', 'price'],
            },
        ),
        migrations.CreateModel(
            name='Rod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='equipment/rods/', verbose_name='Изображение')),
                ('tier', models.CharField(choices=[('basic', 'Базовое'), ('amateur', 'Любительское'), ('professional', 'Профессиональное'), ('expert', 'Экспертное'), ('master', 'Мастерское')], default='basic', max_length=20, verbose_name='Уровень')),
                ('power', models.PositiveIntegerField(help_text='Влияет на контроль крупной рыбы', verbose_name='Мощность (1-100)')),
                ('sensitivity', models.PositiveIntegerField(help_text='Влияет на обнаружение поклёвки', verbose_name='Чувствительность (1-100)')),
                ('max_line_weight', models.FloatField(help_text='Максимальный вес лески', verbose_name='Макс. тест лески (кг)')),
                ('cast_distance_bonus', models.PositiveIntegerField(default=0, verbose_name='Бонус дальности заброса (%)')),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
                ('required_level', models.PositiveIntegerField(default=1, verbose_name='Требуемый уровень')),
                ('durability', models.PositiveIntegerField(default=100, verbose_name='Прочность')),
            ],
            options={
                'verbose_name': 'Удочка',
                'verbose_name_plural': 'Удочки',
                'ordering': ['required_level', 'price'],
            },
        ),
    ]
