# Generated by Django 5.2.10 on 2026-01-16 11:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fishing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('idle', 'Ожидание'), ('casting', 'Заброс'), ('waiting', 'Ожидание поклёвки'), ('bite', 'Поклёвка'), ('fighting', 'Вываживание'), ('catching', 'Подсечка')], default='idle', max_length=20, verbose_name='Состояние')),
                ('cast_distance', models.FloatField(default=0, verbose_name='Дистанция заброса (м)')),
                ('cast_depth', models.FloatField(default=0, verbose_name='Глубина (м)')),
                ('hooked_fish_weight', models.FloatField(default=0, verbose_name='Вес рыбы (кг)')),
                ('fish_state', models.CharField(choices=[('passive', 'Пассивная'), ('active', 'Активная'), ('rush', 'Рывок'), ('exhausted', 'Уставшая')], default='passive', max_length=20, verbose_name='Состояние рыбы')),
                ('fish_stamina', models.FloatField(default=100, verbose_name='Выносливость рыбы (0-100)')),
                ('fish_distance', models.FloatField(default=0, verbose_name='Дистанция до рыбы (м)')),
                ('fish_direction', models.FloatField(default=0, verbose_name='Направление рыбы (градусы)')),
                ('line_tension', models.FloatField(default=0, verbose_name='Натяжение лески (0-100)')),
                ('line_health', models.FloatField(default=100, verbose_name='Здоровье лески (0-100)')),
                ('drag_level', models.FloatField(default=0.5, verbose_name='Уровень фрикциона (0-1)')),
                ('fight_start_time', models.DateTimeField(blank=True, null=True, verbose_name='Начало вываживания')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hooked_fish', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fishing.fish', verbose_name='Рыба на крючке')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fishing.location', verbose_name='Локация')),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='game_session', to=settings.AUTH_USER_MODEL, verbose_name='Игрок')),
            ],
            options={
                'verbose_name': 'Игровая сессия',
                'verbose_name_plural': 'Игровые сессии',
            },
        ),
    ]
