# Generated by Django 5.2.10 on 2026-01-16 11:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fishing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='achievements/', verbose_name='Иконка')),
                ('achievement_type', models.CharField(choices=[('catch_count', 'Количество пойманной рыбы'), ('catch_weight', 'Вес пойманной рыбы'), ('catch_rarity', 'Поймать рыбу редкости'), ('catch_species', 'Поймать определённый вид'), ('level_reach', 'Достичь уровня'), ('money_earn', 'Заработать денег'), ('location_visit', 'Посетить локацию')], max_length=20, verbose_name='Тип')),
                ('target_value', models.PositiveIntegerField(help_text='Например: 100 рыб, 50 кг, уровень 10', verbose_name='Целевое значение')),
                ('target_rarity', models.CharField(blank=True, max_length=20, verbose_name='Целевая редкость')),
                ('reward_money', models.PositiveIntegerField(default=0, verbose_name='Награда деньгами')),
                ('reward_experience', models.PositiveIntegerField(default=0, verbose_name='Награда опытом')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_hidden', models.BooleanField(default=False, help_text='Скрытые достижения не показываются до получения', verbose_name='Скрытое')),
                ('target_fish', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fishing.fish', verbose_name='Целевая рыба')),
                ('target_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fishing.location', verbose_name='Целевая локация')),
            ],
            options={
                'verbose_name': 'Достижение',
                'verbose_name_plural': 'Достижения',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PlayerStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_casts', models.PositiveIntegerField(default=0, verbose_name='Всего забросов')),
                ('successful_catches', models.PositiveIntegerField(default=0, verbose_name='Успешных поимок')),
                ('fish_escaped', models.PositiveIntegerField(default=0, verbose_name='Рыба сорвалась')),
                ('line_breaks', models.PositiveIntegerField(default=0, verbose_name='Обрывов лески')),
                ('common_caught', models.PositiveIntegerField(default=0)),
                ('uncommon_caught', models.PositiveIntegerField(default=0)),
                ('rare_caught', models.PositiveIntegerField(default=0)),
                ('epic_caught', models.PositiveIntegerField(default=0)),
                ('legendary_caught', models.PositiveIntegerField(default=0)),
                ('longest_fight_seconds', models.PositiveIntegerField(default=0, verbose_name='Самое долгое вываживание (сек)')),
                ('fastest_catch_seconds', models.PositiveIntegerField(default=0, verbose_name='Самая быстрая поимка (сек)')),
                ('total_play_time_seconds', models.PositiveIntegerField(default=0, verbose_name='Общее время игры (сек)')),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to=settings.AUTH_USER_MODEL, verbose_name='Игрок')),
            ],
            options={
                'verbose_name': 'Статистика игрока',
                'verbose_name_plural': 'Статистика игроков',
            },
        ),
        migrations.CreateModel(
            name='PlayerAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlocked_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата получения')),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='progression.achievement', verbose_name='Достижение')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL, verbose_name='Игрок')),
            ],
            options={
                'verbose_name': 'Достижение игрока',
                'verbose_name_plural': 'Достижения игроков',
                'unique_together': {('player', 'achievement')},
            },
        ),
    ]
