# Generated by Django 5.2.10 on 2026-01-16 11:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipment', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='locations/', verbose_name='Изображение')),
                ('max_depth', models.FloatField(verbose_name='Максимальная глубина (м)')),
                ('required_level', models.PositiveIntegerField(default=1, verbose_name='Требуемый уровень')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Локация',
                'verbose_name_plural': 'Локации',
                'ordering': ['required_level', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Fish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='fish/', verbose_name='Изображение')),
                ('min_weight', models.FloatField(verbose_name='Минимальный вес (кг)')),
                ('max_weight', models.FloatField(verbose_name='Максимальный вес (кг)')),
                ('rarity', models.CharField(choices=[('common', 'Обычная'), ('uncommon', 'Необычная'), ('rare', 'Редкая'), ('epic', 'Эпическая'), ('legendary', 'Легендарная')], default='common', max_length=20, verbose_name='Редкость')),
                ('base_price', models.PositiveIntegerField(verbose_name='Базовая цена за кг')),
                ('strength', models.PositiveIntegerField(help_text='Сила сопротивления при вываживании', verbose_name='Сила (1-100)')),
                ('stamina', models.PositiveIntegerField(help_text='Как долго рыба может сопротивляться', verbose_name='Выносливость (1-100)')),
                ('aggressiveness', models.PositiveIntegerField(help_text='Частота и сила рывков', verbose_name='Агрессивность (1-100)')),
                ('depth_min', models.FloatField(verbose_name='Минимальная глубина (м)')),
                ('depth_max', models.FloatField(verbose_name='Максимальная глубина (м)')),
                ('active_from', models.PositiveIntegerField(default=0, verbose_name='Активна с (час)')),
                ('active_until', models.PositiveIntegerField(default=24, verbose_name='Активна до (час)')),
                ('locations', models.ManyToManyField(related_name='fish_species', to='fishing.location', verbose_name='Локации')),
            ],
            options={
                'verbose_name': 'Рыба',
                'verbose_name_plural': 'Рыбы',
                'ordering': ['rarity', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CatchRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(verbose_name='Вес (кг)')),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
                ('experience', models.PositiveIntegerField(verbose_name='Опыт')),
                ('caught_at', models.DateTimeField(auto_now_add=True, verbose_name='Время поимки')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catches', to=settings.AUTH_USER_MODEL, verbose_name='Игрок')),
                ('fish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catches', to='fishing.fish', verbose_name='Рыба')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catches', to='fishing.location', verbose_name='Локация')),
            ],
            options={
                'verbose_name': 'Запись улова',
                'verbose_name_plural': 'Записи уловов',
                'ordering': ['-caught_at'],
            },
        ),
        migrations.CreateModel(
            name='FishBaitPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attraction', models.PositiveIntegerField(help_text='0 = не клюёт, 100 = обожает', verbose_name='Привлекательность (0-100)')),
                ('bait', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fish_preferences', to='equipment.bait', verbose_name='Наживка')),
                ('fish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bait_preferences', to='fishing.fish', verbose_name='Рыба')),
            ],
            options={
                'verbose_name': 'Предпочтение наживки',
                'verbose_name_plural': 'Предпочтения наживок',
                'unique_together': {('fish', 'bait')},
            },
        ),
    ]
